/*
 * DotAAS Part 2 | HTTP/REST | Entire API Collection
 *
 * The entire API collection as part of Details of the Asset Administration Shell Part 2
 *
 * OpenAPI spec version: V1.0RC03
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;

namespace IO.Swagger.V1RC03.Models
{ 
        /// <summary>
        /// Gets or Sets LevelType
        /// </summary>
        [JsonConverter(typeof(Newtonsoft.Json.Converters.StringEnumConverter))]
        public enum LevelType
        {
            /// <summary>
            /// Enum MinEnum for Min
            /// </summary>
            [EnumMember(Value = "Min")]
            MinEnum = 0,
            /// <summary>
            /// Enum MaxEnum for Max
            /// </summary>
            [EnumMember(Value = "Max")]
            MaxEnum = 1,
            /// <summary>
            /// Enum NomEnum for Nom
            /// </summary>
            [EnumMember(Value = "Nom")]
            NomEnum = 2,
            /// <summary>
            /// Enum TypEnum for Typ
            /// </summary>
            [EnumMember(Value = "Typ")]
            TypEnum = 3        }
}
