# Use a multi-stage build to build and publish the .NET application
# Specify the initial base architecture (amd64 in this case)
FROM --platform=$BUILDPLATFORM mcr.microsoft.com/dotnet/sdk:8.0.401 AS build-env
WORKDIR /repo/src

# Copy everything else and build
COPY ./src/ /repo/src/
COPY ./LICENSE.TXT /repo/LICENSE.txt

RUN dotnet clean
RUN dotnet restore
RUN dotnet build -o /out/AasxServerBlazor AasxServerBlazor -v d
RUN dotnet publish -c Release -v d --no-restore

# Use a runtime image to run the application
# Specify the initial base architecture (amd64 in this case)
FROM --platform=$BUILDPLATFORM mcr.microsoft.com/dotnet/aspnet:8.0.8 as base
WORKDIR /repo/src
RUN apt update && apt upgrade --yes
RUN apt install -y curl nano libgdiplus
ENV ASPNETCORE_URLS=http://+:5001
ENV ASPNETCORE_HTTP_PORTS=5001
EXPOSE 5001/tcp
EXPOSE 5001/udp
COPY --from=build-env /out/AasxServerBlazor/ /AasxServerBlazor/
COPY ./content-for-demo/ /AasxServerBlazor/
COPY ./src/AasxServerBlazor/appsettings.json /AasxServerBlazor/appsettings.json

WORKDIR /AasxServerBlazor
ENTRYPOINT ["/bin/bash", "-c", "./startForDemo.sh"]
