# Based on https://github.com/dotnet/dotnet-docker/blob/master/samples/dotnetapp/Dockerfile.debian-arm32
FROM mcr.microsoft.com/dotnet/sdk:6.0 AS build-env
WORKDIR /repo/src

# Copy everything else and build
COPY ./src/ /repo/src/
COPY ./LICENSE.TXT /repo/LICENSE.txt

#RUN dotnet restore -r linux-arm64

RUN dotnet publish -c Release -o /out/AasxServerAspNetCore AasxServerAspNetCore -r linux-arm64 --self-contained false

FROM mcr.microsoft.com/dotnet/aspnet:6.0-bullseye-slim-arm64v8
EXPOSE 5001
COPY --from=build-env /out/AasxServerAspNetCore/ /AasxServerAspNetCore/
COPY ./content-for-demo/ /AasxServerAspNetCore/
WORKDIR /AasxServerAspNetCore
ENTRYPOINT ["/bin/bash", "-c", "dotnet AasxServerAspNetCore.dll --no-security --data-path ./aasxs --host 0.0.0.0"]