# It is expected that this docker is executed in the context of repository root.
FROM mcr.microsoft.com/dotnet/core/aspnet:3.1.2-buster-slim-arm32v7 AS build-env
WORKDIR /repo/src

# Copy the source code and build
COPY ./src/ /repo/src/
COPY ./LICENSE.txt /repo/
RUN dotnet publish -r linux-arm -c Release -o /out/AasxServerCoreArm AasxServerCoreArm

FROM mcr.microsoft.com/dotnet/core/aspnet:3.1.2-buster-slim-arm32v7
EXPOSE 51210
EXPOSE 51310
COPY --from=build-env /out/AasxServerCoreArm/ /AasxServerCoreArm/
COPY ./content-for-demo/ /AasxServerCoreArm/
WORKDIR /AasxServerCoreArm
ENTRYPOINT ["/bin/bash", "-c", "./startForDemo.sh"]
