# It is expected that this docker is executed in the context of repository root.
FROM mcr.microsoft.com/dotnet/core/sdk:3.1 AS build-env
WORKDIR /src

# Copy everything else and build
COPY ./src/ /src/
RUN dotnet publish -c Release -o /out/AasxServerCore AasxServerCore

FROM mcr.microsoft.com/dotnet/core/aspnet:3.1
EXPOSE 51210
EXPOSE 51310
WORKDIR /
COPY --from=build-env /out/AasxServerCore/ /AasxServerCore/
ENTRYPOINT ["/bin/bash", "-c", "/AasxServerCore/startForDemo.sh"]
