# It is expected that this docker is executed in the context of repository root.
FROM mcr.microsoft.com/dotnet/sdk:6.0 AS build-env
WORKDIR /repo/src

# Copy the source code and build
COPY ./src/ /repo/src/
COPY ./LICENSE.TXT /repo/LICENSE.txt
RUN dotnet publish -c Release -o /out/AasxServerCore AasxServerCore

FROM mcr.microsoft.com/dotnet/runtime:6.0
EXPOSE 51210
EXPOSE 51310
COPY --from=build-env /out/AasxServerCore/ /AasxServerCore/
COPY ./content-for-demo/ /AasxServerCore/
WORKDIR /AasxServerCore
ENTRYPOINT ["/bin/bash", "-c", "./startForDemo.sh"]
