# It is expected that this docker is executed in the context of repository root.
FROM mcr.microsoft.com/dotnet/sdk:6.0 AS build-env
WORKDIR /repo/src

# Copy everything else and build
COPY ./src/ /repo/src/
COPY ./LICENSE.TXT /repo/LICENSE.txt

RUN dotnet clean
RUN dotnet restore AasxServerBlazor -v diag
RUN dotnet build -o /out/AasxServerBlazor AasxServerBlazor -v diag
RUN dotnet publish -c Release -v diag --no-restore

FROM mcr.microsoft.com/dotnet/aspnet:6.0 as base
RUN apt update && apt upgrade --yes
RUN apt install -y curl nano libgdiplus
EXPOSE 5001
COPY --from=build-env /out/AasxServerBlazor/ /AasxServerBlazor/
COPY ./content-for-demo/ /AasxServerBlazor/
WORKDIR /AasxServerBlazor
ENTRYPOINT ["/bin/bash", "-c", "./startForDemo.sh"]
