# Use a multi-stage build to build and publish the .NET application
FROM --platform=$BUILDPLATFORM mcr.microsoft.com/dotnet/sdk:8.0.401 AS build-env
WORKDIR /repo/src

# Copy the source code and build
COPY ./src/ /repo/src/
COPY ./LICENSE.TXT /repo/LICENSE.txt

RUN dotnet clean
RUN dotnet restore
RUN dotnet build -o /out/AasxServerAspNetCore AasxServerAspNetCore -v d
RUN dotnet publish -c Release -v d --no-restore

# Use a runtime image to run the application
FROM --platform=$BUILDPLATFORM mcr.microsoft.com/dotnet/aspnet:8.0.8 as base
EXPOSE 5001/tcp
EXPOSE 5001/udp
ENV ASPNETCORE_URLS=http://+:5001
COPY --from=build-env /out/AasxServerAspNetCore/ /AasxServerAspNetCore/
COPY ./content-for-demo/ /AasxServerAspNetCore/
WORKDIR /AasxServerAspNetCore
RUN chmod +x ./startForDemo.sh
ENTRYPOINT ["/bin/bash", "-c", "./startForDemo.sh"]
