/* 
 * DotAAS Part 2 | API | Schemas
 *
 * The schemas implementing the [Specification of the Asset Administration Shell: Part 2](http://industrialdigitaltwin.org/en/content-hub).   Publisher: Industrial Digital Twin Association (IDTA) 2023
 *
 * OpenAPI spec version: V3.0.1
 * Contact: info@idtwin.org
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
namespace IO.Swagger.Models
{
    /// <summary>
    /// The Description object enables servers to present their capabilities to the clients, in particular which profiles they implement. At least one defined profile is required. Additional, proprietary attributes might be included. Nevertheless, the server must not expect that a regular client understands them.
    /// </summary>
    [DataContract]
    public partial class ServiceDescription : IEquatable<ServiceDescription>
    {
        /// <summary>
        /// Defines Profiles
        /// </summary>
        [JsonConverter(typeof(StringEnumConverter))]
        public enum ProfilesEnum
        {
            /// <summary>
            /// Enum AssetAdministrationShellServiceSpecificationSSP001 for value: https://admin-shell.io/aas/API/3/0/AssetAdministrationShellServiceSpecification/SSP-001
            /// </summary>
            [EnumMember(Value = "https://admin-shell.io/aas/API/3/0/AssetAdministrationShellServiceSpecification/SSP-001")]
            AssetAdministrationShellServiceSpecificationSSP001 = 1,
            /// <summary>
            /// Enum AssetAdministrationShellServiceSpecificationSSP002 for value: https://admin-shell.io/aas/API/3/0/AssetAdministrationShellServiceSpecification/SSP-002
            /// </summary>
            [EnumMember(Value = "https://admin-shell.io/aas/API/3/0/AssetAdministrationShellServiceSpecification/SSP-002")]
            AssetAdministrationShellServiceSpecificationSSP002 = 2,
            /// <summary>
            /// Enum SubmodelServiceSpecificationSSP001 for value: https://admin-shell.io/aas/API/3/0/SubmodelServiceSpecification/SSP-001
            /// </summary>
            [EnumMember(Value = "https://admin-shell.io/aas/API/3/0/SubmodelServiceSpecification/SSP-001")]
            SubmodelServiceSpecificationSSP001 = 3,
            /// <summary>
            /// Enum SubmodelServiceSpecificationSSP002 for value: https://admin-shell.io/aas/API/3/0/SubmodelServiceSpecification/SSP-002
            /// </summary>
            [EnumMember(Value = "https://admin-shell.io/aas/API/3/0/SubmodelServiceSpecification/SSP-002")]
            SubmodelServiceSpecificationSSP002 = 4,
            /// <summary>
            /// Enum SubmodelServiceSpecificationSSP003 for value: https://admin-shell.io/aas/API/3/0/SubmodelServiceSpecification/SSP-003
            /// </summary>
            [EnumMember(Value = "https://admin-shell.io/aas/API/3/0/SubmodelServiceSpecification/SSP-003")]
            SubmodelServiceSpecificationSSP003 = 5,
            /// <summary>
            /// Enum AasxFileServerServiceSpecificationSSP001 for value: https://admin-shell.io/aas/API/3/0/AasxFileServerServiceSpecification/SSP-001
            /// </summary>
            [EnumMember(Value = "https://admin-shell.io/aas/API/3/0/AasxFileServerServiceSpecification/SSP-001")]
            AasxFileServerServiceSpecificationSSP001 = 6,
            /// <summary>
            /// Enum AssetAdministrationShellRegistryServiceSpecificationSSP001 for value: https://admin-shell.io/aas/API/3/0/AssetAdministrationShellRegistryServiceSpecification/SSP-001
            /// </summary>
            [EnumMember(Value = "https://admin-shell.io/aas/API/3/0/AssetAdministrationShellRegistryServiceSpecification/SSP-001")]
            AssetAdministrationShellRegistryServiceSpecificationSSP001 = 7,
            /// <summary>
            /// Enum AssetAdministrationShellRegistryServiceSpecificationSSP002 for value: https://admin-shell.io/aas/API/3/0/AssetAdministrationShellRegistryServiceSpecification/SSP-002
            /// </summary>
            [EnumMember(Value = "https://admin-shell.io/aas/API/3/0/AssetAdministrationShellRegistryServiceSpecification/SSP-002")]
            AssetAdministrationShellRegistryServiceSpecificationSSP002 = 8,
            /// <summary>
            /// Enum SubmodelRegistryServiceSpecificationSSP001 for value: https://admin-shell.io/aas/API/3/0/SubmodelRegistryServiceSpecification/SSP-001
            /// </summary>
            [EnumMember(Value = "https://admin-shell.io/aas/API/3/0/SubmodelRegistryServiceSpecification/SSP-001")]
            SubmodelRegistryServiceSpecificationSSP001 = 9,
            /// <summary>
            /// Enum SubmodelRegistryServiceSpecificationSSP002 for value: https://admin-shell.io/aas/API/3/0/SubmodelRegistryServiceSpecification/SSP-002
            /// </summary>
            [EnumMember(Value = "https://admin-shell.io/aas/API/3/0/SubmodelRegistryServiceSpecification/SSP-002")]
            SubmodelRegistryServiceSpecificationSSP002 = 10,
            /// <summary>
            /// Enum DiscoveryServiceSpecificationSSP001 for value: https://admin-shell.io/aas/API/3/0/DiscoveryServiceSpecification/SSP-001
            /// </summary>
            [EnumMember(Value = "https://admin-shell.io/aas/API/3/0/DiscoveryServiceSpecification/SSP-001")]
            DiscoveryServiceSpecificationSSP001 = 11,
            /// <summary>
            /// Enum AssetAdministrationShellRepositoryServiceSpecificationSSP001 for value: https://admin-shell.io/aas/API/3/0/AssetAdministrationShellRepositoryServiceSpecification/SSP-001
            /// </summary>
            [EnumMember(Value = "https://admin-shell.io/aas/API/3/0/AssetAdministrationShellRepositoryServiceSpecification/SSP-001")]
            AssetAdministrationShellRepositoryServiceSpecificationSSP001 = 12,
            /// <summary>
            /// Enum AssetAdministrationShellRepositoryServiceSpecificationSSP002 for value: https://admin-shell.io/aas/API/3/0/AssetAdministrationShellRepositoryServiceSpecification/SSP-002
            /// </summary>
            [EnumMember(Value = "https://admin-shell.io/aas/API/3/0/AssetAdministrationShellRepositoryServiceSpecification/SSP-002")]
            AssetAdministrationShellRepositoryServiceSpecificationSSP002 = 13,
            /// <summary>
            /// Enum SubmodelRepositoryServiceSpecificationSSP001 for value: https://admin-shell.io/aas/API/3/0/SubmodelRepositoryServiceSpecification/SSP-001
            /// </summary>
            [EnumMember(Value = "https://admin-shell.io/aas/API/3/0/SubmodelRepositoryServiceSpecification/SSP-001")]
            SubmodelRepositoryServiceSpecificationSSP001 = 14,
            /// <summary>
            /// Enum SubmodelRepositoryServiceSpecificationSSP002 for value: https://admin-shell.io/aas/API/3/0/SubmodelRepositoryServiceSpecification/SSP-002
            /// </summary>
            [EnumMember(Value = "https://admin-shell.io/aas/API/3/0/SubmodelRepositoryServiceSpecification/SSP-002")]
            SubmodelRepositoryServiceSpecificationSSP002 = 15,
            /// <summary>
            /// Enum SubmodelRepositoryServiceSpecificationSSP003 for value: https://admin-shell.io/aas/API/3/0/SubmodelRepositoryServiceSpecification/SSP-003
            /// </summary>
            [EnumMember(Value = "https://admin-shell.io/aas/API/3/0/SubmodelRepositoryServiceSpecification/SSP-003")]
            SubmodelRepositoryServiceSpecificationSSP003 = 16,
            /// <summary>
            /// Enum SubmodelRepositoryServiceSpecificationSSP004 for value: https://admin-shell.io/aas/API/3/0/SubmodelRepositoryServiceSpecification/SSP-004
            /// </summary>
            [EnumMember(Value = "https://admin-shell.io/aas/API/3/0/SubmodelRepositoryServiceSpecification/SSP-004")]
            SubmodelRepositoryServiceSpecificationSSP004 = 17,
            /// <summary>
            /// Enum ConceptDescriptionServiceSpecificationSSP001 for value: https://admin-shell.io/aas/API/3/0/ConceptDescriptionServiceSpecification/SSP-001
            /// </summary>
            [EnumMember(Value = "https://admin-shell.io/aas/API/3/0/ConceptDescriptionServiceSpecification/SSP-001")]
            ConceptDescriptionServiceSpecificationSSP001 = 18
        }
        /// <summary>
        /// Gets or Sets Profiles
        /// </summary>
        [DataMember(Name = "profiles", EmitDefaultValue = false)]
        public List<ProfilesEnum> Profiles { get; set; }
        /// <summary>
        /// Initializes a new instance of the <see cref="ServiceDescription" /> class.
        /// </summary>
        /// <param name="profiles">profiles.</param>
        public ServiceDescription(List<ProfilesEnum> profiles = default(List<ProfilesEnum>))
        {
            this.Profiles = profiles;
        }


        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class ServiceDescription {\n");
            sb.Append("  Profiles: ").Append(Profiles).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as ServiceDescription);
        }

        /// <summary>
        /// Returns true if ServiceDescription instances are equal
        /// </summary>
        /// <param name="input">Instance of ServiceDescription to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(ServiceDescription input)
        {
            if (input == null)
                return false;

            return
                (
                    this.Profiles == input.Profiles ||
                    this.Profiles != null &&
                    input.Profiles != null &&
                    this.Profiles.SequenceEqual(input.Profiles)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Profiles != null)
                    hashCode = hashCode * 59 + this.Profiles.GetHashCode();
                return hashCode;
            }
        }

    }
}
