/*
 * DotAAS Part 2 | HTTP/REST | Asset Administration Shell Repository
 *
 * An exemplary interface combination for the use case of an Asset Administration Shell Repository
 *
 * OpenAPI spec version: Final-Draft
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Runtime.Serialization;
using System.Text;
using Newtonsoft.Json;

namespace IO.Swagger.Models
{
    /// <summary>
    /// 
    /// </summary>
    [DataContract]
    public partial class ValueList : IEquatable<ValueList>
    {
        /// <summary>
        /// Gets or Sets ValueReferencePairTypes
        /// </summary>
        [Required]

        [DataMember(Name = "valueReferencePairTypes")]
        public List<ValueReferencePairType> ValueReferencePairTypes { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class ValueList {\n");
            sb.Append("  ValueReferencePairTypes: ").Append(ValueReferencePairTypes).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            if (ReferenceEquals(null, obj)) return false;
            if (ReferenceEquals(this, obj)) return true;
            return obj.GetType() == GetType() && Equals((ValueList)obj);
        }

        /// <summary>
        /// Returns true if ValueList instances are equal
        /// </summary>
        /// <param name="other">Instance of ValueList to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(ValueList other)
        {
            if (ReferenceEquals(null, other)) return false;
            if (ReferenceEquals(this, other)) return true;

            return
                (
                    ValueReferencePairTypes == other.ValueReferencePairTypes ||
                    ValueReferencePairTypes != null &&
                    ValueReferencePairTypes.SequenceEqual(other.ValueReferencePairTypes)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                var hashCode = 41;
                // Suitable nullity checks etc, of course :)
                if (ValueReferencePairTypes != null)
                    hashCode = hashCode * 59 + ValueReferencePairTypes.GetHashCode();
                return hashCode;
            }
        }

        #region Operators
#pragma warning disable 1591

        public static bool operator ==(ValueList left, ValueList right)
        {
            return Equals(left, right);
        }

        public static bool operator !=(ValueList left, ValueList right)
        {
            return !Equals(left, right);
        }

#pragma warning restore 1591
        #endregion Operators
    }
}
