// <auto-generated />
using AasxServerDB;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AasxServerStandardBib.Migrations.Sqlite
{
    [DbContext(typeof(SqliteAasContext))]
    [Migration("20230904082908_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.5");

            modelBuilder.Entity("AasxServer.AASXSet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AASX")
                        .HasColumnType("TEXT");

                    b.Property<long>("AASXNum")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("AASXNum");

                    b.ToTable("AASXSets");
                });

            modelBuilder.Entity("AasxServer.AASSet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("AASXNum")
                        .HasColumnType("INTEGER");

                    b.Property<string>("AASId")
                        .HasColumnType("TEXT");

                    b.Property<long>("AASNum")
                        .HasColumnType("INTEGER");

                    b.Property<string>("GlobalAssetId")
                        .HasColumnType("TEXT");

                    b.Property<string>("AssetKind")
                        .HasColumnType("TEXT");

                    b.Property<string>("IdShort")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AASNum");

                    b.ToTable("AASSets");
                });

            modelBuilder.Entity("AasxServer.DBConfigSet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("AASXCount")
                        .HasColumnType("INTEGER");

                    b.Property<long>("AASCount")
                        .HasColumnType("INTEGER");

                    b.Property<long>("SMECount")
                        .HasColumnType("INTEGER");

                    b.Property<long>("SubmodelCount")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("DBConfigSets");
                });

            modelBuilder.Entity("AasxServer.DoubleValue", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Annotation")
                        .HasColumnType("TEXT");

                    b.Property<long>("ParentSMENum")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Value")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("ParentSMENum");

                    b.ToTable("DValueSets");
                });

            modelBuilder.Entity("AasxServer.IntValue", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Annotation")
                        .HasColumnType("TEXT");

                    b.Property<long>("ParentSMENum")
                        .HasColumnType("INTEGER");

                    b.Property<long>("Value")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ParentSMENum");

                    b.ToTable("IValueSets");
                });

            modelBuilder.Entity("AasxServer.SMESet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("IdShort")
                        .HasColumnType("TEXT");

                    b.Property<long>("ParentSMENum")
                        .HasColumnType("INTEGER");

                    b.Property<long>("SMENum")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SMEType")
                        .HasColumnType("TEXT");

                    b.Property<string>("SemanticId")
                        .HasColumnType("TEXT");

                    b.Property<long>("SMNum")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ValueType")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SMENum");

                    b.HasIndex("SMNum");

                    b.ToTable("SMESets");
                });

            modelBuilder.Entity("AasxServer.StringValue", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Annotation")
                        .HasColumnType("TEXT");

                    b.Property<long>("ParentSMENum")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Value")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ParentSMENum");

                    b.ToTable("SValueSets");
                });

            modelBuilder.Entity("AasxServer.SMSet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("AASXNum")
                        .HasColumnType("INTEGER");

                    b.Property<long>("AASNum")
                        .HasColumnType("INTEGER");

                    b.Property<string>("IdShort")
                        .HasColumnType("TEXT");

                    b.Property<string>("SemanticId")
                        .HasColumnType("TEXT");

                    b.Property<string>("SMId")
                        .HasColumnType("TEXT");

                    b.Property<long>("SMNum")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("SMNum");

                    b.ToTable("SMSets");
                });
#pragma warning restore 612, 618
        }
    }
}
