// <auto-generated />
using AasxServerDB;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AasxServerDB.Migrations.Sqlite
{
    [DbContext(typeof(SqliteAasContext))]
    [Migration("20240311072108_Change")]
    partial class Change
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.5");

            modelBuilder.Entity("AasxServerDB.AASXSet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AASX")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("AASXNum")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("AASXNum");

                    b.ToTable("AASXSets");
                });

            modelBuilder.Entity("AasxServerDB.AasSet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("AASXNum")
                        .HasColumnType("INTEGER");

                    b.Property<string>("AasId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("AasNum")
                        .HasColumnType("INTEGER");

                    b.Property<string>("AssetId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("AssetKind")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Idshort")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AasNum");

                    b.ToTable("AasSets");
                });

            modelBuilder.Entity("AasxServerDB.DbConfigSet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("AASXCount")
                        .HasColumnType("INTEGER");

                    b.Property<long>("AasCount")
                        .HasColumnType("INTEGER");

                    b.Property<long>("SMECount")
                        .HasColumnType("INTEGER");

                    b.Property<long>("SubmodelCount")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("DbConfigSets");
                });

            modelBuilder.Entity("AasxServerDB.DoubleValue", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Annotation")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("ParentSMENum")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Value")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("ParentSMENum");

                    b.ToTable("DValueSets");
                });

            modelBuilder.Entity("AasxServerDB.IntValue", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Annotation")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("ParentSMENum")
                        .HasColumnType("INTEGER");

                    b.Property<long>("Value")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ParentSMENum");

                    b.ToTable("IValueSets");
                });

            modelBuilder.Entity("AasxServerDB.SMESet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Idshort")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("ParentSMENum")
                        .HasColumnType("INTEGER");

                    b.Property<long>("SMENum")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SMEType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SemanticId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("SubmodelNum")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ValueType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SMENum");

                    b.HasIndex("SubmodelNum");

                    b.ToTable("SMESets");
                });

            modelBuilder.Entity("AasxServerDB.StringValue", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Annotation")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("ParentSMENum")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ParentSMENum");

                    b.ToTable("SValueSets");
                });

            modelBuilder.Entity("AasxServerDB.SubmodelSet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("AASXNum")
                        .HasColumnType("INTEGER");

                    b.Property<long>("AasNum")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Idshort")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SemanticId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SubmodelId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("SubmodelNum")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("SubmodelNum");

                    b.ToTable("SubmodelSets");
                });
#pragma warning restore 612, 618
        }
    }
}
