/*
 * DotAAS Part 2 | HTTP/REST | Repository Service Specification
 *
 * The entire Repository Service Specification as part of Details of the Asset Administration Shell Part 2
 *
 * OpenAPI spec version: V3.0
 *
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.IO;
using Microsoft.AspNetCore.Builder;
using Microsoft.AspNetCore.Hosting;
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.Hosting;
using Microsoft.Extensions.Logging;
using Microsoft.OpenApi.Models;
using IO.Swagger.Filters;


namespace IO.Swagger;

using System.Collections.Generic;
using System.Text.Json;
using System.Text.Json.Serialization;
using Microsoft.AspNetCore.Mvc.Formatters;
using Microsoft.OpenApi.Any;
using Models;

/// <summary>
/// Startup
/// </summary>
public class Startup
{
    private readonly IWebHostEnvironment _hostingEnv;

    private IConfiguration Configuration { get; }

    /// <summary>
    /// Constructor
    /// </summary>
    /// <param name="env"></param>
    /// <param name="configuration"></param>
    public Startup(IWebHostEnvironment env, IConfiguration configuration)
    {
        _hostingEnv   = env;
        Configuration = configuration;
    }

    /// <summary>
    /// This method gets called by the runtime. Use this method to add services to the container.
    /// </summary>
    /// <param name="services"></param>
    public void ConfigureServices(IServiceCollection services)
    {
        // Add framework services.
        services
            .AddMvc(options =>
                    {
                        // Remove System.Text.Json formatters
                        options.InputFormatters.RemoveType<SystemTextJsonInputFormatter>();
                        options.OutputFormatters.RemoveType<SystemTextJsonOutputFormatter>();
                    })
            .AddJsonOptions(options =>
                            {
                                // Configure System.Text.Json settings
                                options.JsonSerializerOptions.PropertyNamingPolicy = JsonNamingPolicy.CamelCase;
                                options.JsonSerializerOptions.Converters.Add(new JsonStringEnumConverter());
                                options.JsonSerializerOptions.IgnoreNullValues = true;
                            })
            .AddXmlSerializerFormatters();

        services.AddSwaggerGen(c =>
                               {
                                   c.SwaggerDoc("V3.0",
                                                new OpenApiInfo
                                                {
                                                    Version     = "V3.0",
                                                    Title       = "DotAAS Part 2 | HTTP/REST | Repository Service Specification",
                                                    Description = "DotAAS Part 2 | HTTP/REST | Repository Service Specification (ASP.NET Core 3.1)",
                                                    Contact = new OpenApiContact()
                                                              {
                                                                  Name
                                                                      = "Constantin Ziesche, Andreas Orzelski, Florian Krebs, Bastian Rössl, Manuel Sauer, Jens Vialkowitsch, Michael Hoffmeister, Torben Miny, Sebastian Bader, Marko Ristin, Nico Braunisch",
                                                                  Url   = new Uri("https://github.com/swagger-api/swagger-codegen"),
                                                                  Email = ""
                                                              },
                                                    TermsOfService = new Uri("https://github.com/admin-shell-io/aas-specs")
                                                });

                                   c.CustomSchemaIds(type => type.FullName);
                                   c.IncludeXmlComments($"{AppContext.BaseDirectory}{Path.DirectorySeparatorChar}{_hostingEnv.ApplicationName}.xml");

                                   // Include DataAnnotation attributes on Controller Action parameters as Swagger validation rules
                                   c.OperationFilter<GeneratePathParamsValidationFilter>();
                               });
    }


    /// <summary>
    /// This method gets called by the runtime. Use this method to configure the HTTP request pipeline.
    /// </summary>
    /// <param name="app"></param>
    /// <param name="env"></param>
    /// <param name="loggerFactory"></param>
    public void Configure(IApplicationBuilder app, IWebHostEnvironment env, ILoggerFactory loggerFactory)
    {
        app.UseRouting();

        //TODO: Uncomment this if you need wwwroot folder
        // app.UseStaticFiles();

        app.UseAuthorization();

        app.UseSwagger();
        app.UseSwaggerUI(c =>
                         {
                             //TODO: Either use the SwaggerGen generated Swagger contract (generated from C# classes)
                             c.SwaggerEndpoint("/swagger/V3.0/swagger.json", "DotAAS Part 2 | HTTP/REST | Repository Service Specification");

                             //TODO: Or alternatively use the original Swagger contract that's included in the static files
                             // c.SwaggerEndpoint("/swagger-original.json", "DotAAS Part 2 | HTTP/REST | Repository Service Specification Original");
                         });

        //TODO: Use Https Redirection
        // app.UseHttpsRedirection();

        app.UseEndpoints(endpoints =>
                         {
                             endpoints.MapControllers();
                         });

        if (env.IsDevelopment())
        {
            app.UseDeveloperExceptionPage();
        }
        else
        {
            //TODO: Enable production exception handling (https://docs.microsoft.com/en-us/aspnet/core/fundamentals/error-handling)
            app.UseExceptionHandler("/Error");

            app.UseHsts();
        }
    }
}