/*
 * DotAAS Part 2 | HTTP/REST | Asset Administration Shell Environment API
 *
 * An exemplary API combination for the use case of an Asset Administration Shell Environment
 *
 * OpenAPI spec version: V1.0RC03
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using HttpContext = Microsoft.AspNetCore.Http.HttpContext;

namespace IO.Swagger.V1RC03.Controllers
{
    public partial class AssetAdministrationShellEnvironmentAPIController
    {
        public class AasSecurityContext
        {
            public string accessRights;
            public string route;
            public string neededRights;
            public AasSecurityContext(string _acccessRights, string _route, string _httpOperation)
            {
                accessRights = _acccessRights;
                route = _route;
                switch (_httpOperation)
                {
                    case "POST":
                        neededRights = "CREATE";
                        break;
                    case "GET":
                        neededRights = "READ";
                        break;
                    case "PUT":
                        neededRights = "UPDATE";
                        break;
                    case "DELETE":
                        neededRights = "DELETE";
                        break;
                }
            }
        }
    }
}
